version: "2"
services:
  jenkins:
    image: jenkinsci/blueocean
    user: root
    ports:
      - "80:8080"
      - "443:8443"
      - "50000:50000"
    volumes:
      - ./jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock